### ISSUE TITLE
Request: User search by name API

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#115]
Hi,
are there any plans or is it possible currently to search users by name?

**Comment by muteor** [comment]
We have actually experimented a couple of times with user search, each time its failed for various reasons. It's one of those things that seems simple until you actually build it, we found that because there are so many users providing the correct relevancy was non-trivial. So, for that reason I very much doubt we will be building this anytime soon.
