### ISSUE TITLE
/browse/any

### ISSUE THREAD

**Issue by arthursteblin** [DeviantArt/DeviantArt-API#123]
Hi!

In the description of the method is written that "The pagination limit min: 1 max: 120 default: 10". In fact I can get max 24 elements in an array. Is it a mistake in the description?

Exp.
GET https://www.deviantart.com/api/v1/oauth2/browse/hot?limit=120&mature_content=true

Answer:
{
    "has_more": true,
    "next_offset": 24,
    "results": [array]
        {
}}

**Comment by floriangaerber** [comment]
*Not a DeviantArt Developer*, but this is probably because getting larger amounts of elements is limited to Core Members on the website, as you can see in your Account Settings / Browsing page: https://www.deviantart.com/settings/browsing (Display: Thumbnails per page)
I assume this limit also applies to the API.

**Comment by TheDefinitionist** [comment]
I assume they narrowed it down to 24 due massive traffic or anything alike which is kinda meh... even the offset is limited to 40k/16k now which means a lot of them you ain't able to fetch when you browse deviations. Around 960k is max while over 360milion artworks exist...

**Comment by muteor** [comment]
Yeah this is due to core member settings.
