### ISSUE TITLE
Deviation/WhoFaved order

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#41]
Is there any order in which users are retrieved? For example, by fave date, or in alphanumerical order?

**Comment by KarsonKimbrel** [comment]
Just by looking at the response I can tell you it is not by fave date or by alphanumerical order.

**Comment by galymzhan** [comment]
Nope, they're not ordered

**Comment by muteor** [comment]
We may remove this endpoint for now, we never ended up using it and ordering is not easy to add because of the way faves are stored. Looking at the stats you are the only person to ever test it out :) Sorry to have to do that but some endpoints we did not test fully slipped through when we released the api publicly.

**Comment by Viachaslau-Zinkevich** [comment]
Wow, never thought that no one would even care who faved them, at least to thank them, as it is usually done on web-site).

**Comment by shiyunhe** [comment]
Please don't remove the end point. I am using it in my app.

A user can find who faved their deviation through notification (end point: GET /feed/notifications)

**Comment by parallellogic-** [comment]
Favs are sorted by when the user joined the site.
