### ISSUE TITLE
Journal inner deviations ids

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#45]
Hi, I have a question about the journals. As far as I understood, to show the journal content the only option is to get its html content through deviations/content api, am I right? If this is it I wonder how the to get a DeviationId when user clicks the link there? In android app as I've seen, when clicking the deviation app automatically navigates to details page with deviation, not in browser. Is it possible to create the same behavior? As far as I've seen, the link itself doesn't have any id in it..

**Comment by muteor** [comment]
Yes the html and css will be returned from /content this is the way to display journals. Links contained in the HTML are a different story. We are currently working on creating a way to return HTML in a structured format (bit like an AST) so that links and embedded content can be handled easily. Not sure on an ETA for that I would hope it will be ready for public release in the next few months.

**Comment by Viachaslau-Zinkevich** [comment]
No, I understand that I need to display the data of journals as html. The problem is, if there a way to get deviation Id from link, may be? For example, if in Android app I click a link in a journal -- the deviation will be opened in application, not in browser. How can this be achieved?

**Comment by Viachaslau-Zinkevich** [comment]
And what does exactly do /embeddedcontent? I thought it would return all the deviations inside the journal, but as far as I saw -- it doesn't, but has a lot of other different deviations, which I can't connect to each other.
